### ISSUE TITLE
showing "no points/faces were imported"

### ISSUE THREAD

**Issue by lcs503** [tkeskita/io_mesh_vtk#1]
blender 2.80
importing vtk file:
https://people.sc.fsu.edu/~jburkardt/data/vtk/rbc_001.vtk
showing "no points/faces were imported"

**Comment by tkeskita** [comment]
Hi,

your vtk file contains unstructured grid and not polydata, as expected by io_mesh_vtk. Your options are:
1. Convert unstructured grid to polydata and export that as .vtk. This can be done e.g. in Paraview by applying filter "Extract Surfaces". Or
2. Use BVTKNodes. You can read your vtk file in using node "vtkUnstructuredGridReader" and then connect that to "VTK To Blender" node.

**Comment by tkeskita** [comment]
FYI, I committed improved error messages for the add-on so errors due to unsupported data or formats are communicated better. Thanks!
